#!/usr/bin/env bash
# ripped from pulseaudio-ctl
volume=$(pacmd list-sinks|grep -A 15 '* index'|grep 'volume: '|grep -o '[0-9]\+%'|grep -m 1 %|sed 's/[%|,]//g')

echo "${volume}%"
echo "${volume}%"
echo ""

if [[ "${volume}" -gt 100 ]]; then
  exit 33
fi
