#!/usr/bin/env bash
# Original inspiration:
# https://github.com/Airblader/dotfiles-manjaro/blob/master/scripts/battery.sh

ACPI=$(acpi -b)
[[ -z $ACPI ]] && exit
CHARGE=$(echo -n "${ACPI}" | egrep -o "[0-9]+%" | sed -e "s,%,,g")

if grep -q "Charging\|Full" <(echo "${ACPI}" | awk '{ gsub("Unknown","Charging",$3); print $3}'); then
    STATE=""
else
    STATE=$(echo "${ACPI}" | awk '{print $3}' | sed -e "s%,%%g")
    STATE=" (${STATE})"
fi

LEVEL=$(( (CHARGE - 1) / 20 ))
ICON="f$(( 244 - LEVEL ))"
grep -q "Charging" <(echo "${ACPI}") && ICON="f0e7" #fa-bolt

echo -e "  \u${ICON}  ${CHARGE}%${STATE} "

[[ "${LEVEL}" = "0" ]] && {
    [[ -z "${STATE}" ]] || i3-msg "fullscreen disable"
    exit 33
}

exit 0
