#!/usr/bin/env bash

INSTANCE="${BLOCK_INSTANCE:-1}"

URGENT_VALUE=$(nproc)

LOAD=$(cat /proc/loadavg | awk -F ' ' '{print $'"${INSTANCE}"'}')

echo "${LOAD}"
echo "${LOAD}"
echo ""

if [[ "${LOAD%.*}" -ge "${URGENT_VALUE}" ]]; then
  exit 33
fi

