misc:
  auto_exit: no
  use_autorun: no
  show_passwords: yes
  expect_timeout: 60
  nailsURL: http://nails.rackersupport.com
  assumerdpwin: yes
terminal:
  expect_path: /usr/bin/expect
  terminal: tmux
  tmux_layout: tiled
  tmux_max_panes: 9
  use_colors: yes
  rdpwin_path: /home/stephen/.local/bin/rdpwin
authentication:
  intensive_ad_become_root: yes
  username: step7212
  browser: firefox
