#!/bin/bash

stowpkgs=()

if [[ $# = 1 ]]; then
  if [[ $1 = "home" ]]; then
    echo "It's home time"
    stowpkgs+=(bash bin dupeGuru git gtk2 gtk3 pics rack remind shell sublime-text-3 terminator termite tmux vim zgen zsh)
  elif [[ $1 = "work" ]]; then
    echo "It's workin time!"
    stowpkgs+=(bash bin git gtk2 gtk3 pics rack remind shell sublime-text-3 terminator termite tmux vim zgen zsh)
    stowpkgs+=(cava compton hammercloud i3 i3blocks i3lock overtime sway volumectl work)
  fi
else
  echo "Please choose 'home' or 'work'"
  exit
fi
stow -Rv ${stowpkgs[@]}
