#!/bin/bash

## Source:
# Shamelessly ripped and modified from
# https://bitbucket.org/tim_heap/.dot-files/src/20b62512624e/create-links
##

for file in [a-zA-Z]* ; do
    if [[ "$file" != "create-links" && "$file" != "README" && "$file" != "README.md" ]] ; then

        if [[ -h ~/."$file" ]] ; then
            echo "  Removing symbolic link ~/.$file"
            rm ~/."$file"
        elif [[ -a ~/."$file" ]] ; then
            date=$(date '+%FT%T');
            echo "  ~/.$file exists. Moving it to ~/.$file.back.$date"
            mv ~/."$file" ~/."$file".back.$date || echo "Couldn't move ~/.$file to ~/.$file.back.$date!"
        fi

        ln -s `pwd`/"$file" ~/."$file" && echo "Linked ~/.$file to `pwd`/$file" || echo "Couldn't link ~/.$file to `pwd`/$file!"
    fi
done
