#!/usr/bin/env python
import os
import re
import json
import subprocess
outputs = json.loads(subprocess.getoutput('swaymsg -t get_outputs'))

defaultName = [ out for out in outputs if re.match(r'default', out['name']) ]
hdmiName = [ out for out in outputs if re.match(r'HDMI', out['name']) ]
vgaName = [ out for out in outputs if re.match(r'VGA', out['name']) ]
edpName = [ out for out in outputs if re.match(r'EDP', out['name']) ]
dpName = [ out for out in outputs if re.match(r'^DP', out['name']) and re.match(r'EDP', out['name']) is None ]

activeDisplays = [ out for out in outputs if out['active'] ]

displayFile = '/tmp/.displays'

if os.path.isfile(displayFile):
    with open(displayFile) as df:
        oldDisplays = json.loads(df.read())
else:
    oldDisplays = ""

if not oldDisplays == activeDisplays:
    change="yes"
else:
    change="no"

print(' '.join([out['name'] for out in activeDisplays]))
print(' '.join([out['name'] for out in activeDisplays]))
print('')
