#!/bin/bash

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  sudo systemctl enable firewalld
  sudo systemctl start firewalld
# Middle click
elif [[ "${BLOCK_BUTTON}" -eq 2 ]]; then
  sudo firewall-cmd --reload
# Right click
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  sudo systemctl disable firewalld
  sudo systemctl stop firewalld
fi

status=$(sudo firewall-cmd --state 2>/dev/null)

if [[ "${status}" != *not* ]]; then
  echo "on"
  echo "on"
  echo ""
else
  echo "off"
  echo "off"
  echo ""
fi
