#!/usr/bin/env bash
# Based on http://openweathermap.org/current

API_KEY="2de143494c0b295cca9337e1e96b00e0"

MURICA=true

if [[ "${MURICA}" = true ]]; then
    URGENT_LOWER=32
    URGENT_HIGHER=100
    UNITS="imperial"
    SYMBOL="℉"
else
    URGENT_LOWER=0
    URGENT_HIGHER=37
    SYMBOL="℃"
    UNITS="metric"
fi

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""

# Check on http://openweathermap.org/find
BASE_URL="http://api.openweathermap.org/data/2.5/weather?appid=${API_KEY}&units=${UNITS}"
INSTANCE="${BLOCK_INSTANCE:-4726206}"

if [[ "${INSTANCE}" =~ ^[0-9]{7}$ ]]; then
    CITY_ID=${INSTANCE}
    WEATHER_URL="${BASE_URL}&id=${CITY_ID}"
elif [[ "${INSTANCE}" =~ ^[0-9]{5}$ ]]; then
    CITY_ZIP=${INSTANCE}
    WEATHER_URL="${BASE_URL}&zip=${CITY_ZIP}"
elif [[ "${INSTANCE}" =~ ^([0-9]{5}),([a-zA-Z]{2})$ ]]; then
    CITY_ZIP=${BASH_REMATCH[1]}
    COUNTRY_CODE=${BASH_REMATCH[2]}
    WEATHER_URL="${BASE_URL}&zip=${CITY_ZIP},${COUNTRY_CODE}"
elif [[ "${INSTANCE}" =~ ^([0-9.-]+),([0-9.-]+)$ ]]; then
    LAT=${BASH_REMATCH[1]}
    LON=${BASH_REMATCH[2]}
    WEATHER_URL="${BASE_URL}&lat=${LAT}&lon=${LON}"
elif [[ "${INSTANCE}" =~ ^([a-zA-Z ]+),([a-zA-Z]{2})$ ]]; then
    CITY_NAME=$( echo "${BASH_REMATCH[1]}" | sed 's/ /%20/g')
    COUNTRY_CODE=${BASH_REMATCH[2]}
    WEATHER_URL="${BASE_URL}&q=${CITY_NAME},${COUNTRY_CODE}"
else
    echo "Didn't match anything."
    echo "This should never happen."
    exit 22
fi

WEATHER_INFO=$(curl -s "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | jshon -e weather -a -e main -u)
WEATHER_DESC=$(echo "${WEATHER_INFO}" | jshon -e weather -a -e description -u)
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | jshon -e main -e temp | awk '{printf "%.2f", $1}')
WEATHER_ICON=$(echo "${WEATHER_INFO}" | jshon -e weather -a icon)
ICON_URL="http://openweathermap.org/img/w/${WEATHER_ICON}.png"

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${ICON_SNOW} ${WEATHER_DESC} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL}"
  echo ""
  exit 33
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${ICON_RAINY} ${WEATHER_DESC} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  echo "${ICON_CLOUDY} ${WEATHER_DESC} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${ICON_SUNNY} ${WEATHER_DESC} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL}"
  echo ""
fi

if [[ "${WEATHER_TEMP%.*}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP%.*}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
