export USER=$(whoami)
export HOME=/home/${USER}
export XDG_CONFIG_HOME=${HOME}/.config
export ZPLUG_HOME=${XDG_CONFIG_HOME}/zplug

export ZDOTDIR=${XDG_CONFIG_HOME}/zsh

export SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass

export TIME_STYLE=long-iso

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM='verbose'
export GIT_PS1_DESCRIBE_STYLE='branch'
export GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_HIDE_IF_PWD_IGNORED=true

export EDITOR=vim
export VISUAL=vim

export XZ_OPT="--threads=0"

export SLACK_CLI_TOKEN=

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/dev
source /usr/bin/virtualenvwrapper.sh
